### PR TITLE
Added support for requesting a block by Id.

### PR DESCRIPTION
**Pull request by mjohnson12**
Added `blockNumOrIdString` to `EosioRpcBlockRequest`.
Deprecated `UInt64` `blockNumOrId` since it doesn’t really support block ids since they are strings.

The `EosioRpcBlockRequest` `init` parameter was named `blockNumOrId` but it was of the type `UInt64` so you couldn't actually request a block by id.  In the RPC docs the parameter is defined as a string and can take either a block num or a block id.

This change deprecates requesting a block by `UInt64` and adds support for requesting a block by id or num using a `String` parameter.

The original `blockNumOrId` property is changed to be a computed property and to store and return the value of the new `blockNumOrIdString` property.

I'm not thrilled with the name of the new property `blockNumOrIdString` since the better name would really be the original name but that has to remain for backward compatibility.  I'm open to suggestions for a better name for the property.  Other options I can think of would be: `blockNumberOrId`, `blockNumOrBlockId`.

### CODE REVIEW

**Comment by opi-smccoole** [comment]
You could possibly use EosioUInt64 type since it supports UInt64 or String?

**Comment by mjohnson12** [comment]
> You could possibly use EosioUInt64 type since it supports UInt64 or String?

Yeah I started with `EosioUInt64` but it only supports getting the value as an `UInt64` so it's really for a scenario where you know you have a number but it could be a string or an `UInt64`.

**Comment by mjohnson12** [comment]
Changed this PR to base off of `develop`.

**Comment by opi-smccoole** [comment]
> > You could possibly use EosioUInt64 type since it supports UInt64 or String?
> 
> Yeah I started with `EosioUInt64` but it only supports getting the value as an `UInt64` so it's really for a scenario where you know you have a number but it could be a string or an `UInt64`.

We could just write a similar type that doesn't force the value as an UInt64 and just use that couldn't we?

**Comment by mjohnson12** [comment]
> > > You could possibly use EosioUInt64 type since it supports UInt64 or String?
> > 
> > 
> > Yeah I started with `EosioUInt64` but it only supports getting the value as an `UInt64` so it's really for a scenario where you know you have a number but it could be a string or an `UInt64`.
> 
> We could just write a similar type that doesn't force the value as an UInt64 and just use that couldn't we?

Sure.  One option is to make a block identifier type (possibly enum)  that can be either an `UInt64` or a `String`.

**Comment by opi-smccoole** [comment]
I guess it doesn't matter in the end I suppose but the ability to take either saves them having to convert it but the enum isn't as straight forward to use.  I was thinking if the type allowed either that it might make a case for keeping the same parameter name.  But then I realized that the pods are versioned so someone can always use the older one until they can update, so I'm wondering if we just can't go ahead and make blockNumOrId into a String?

**Comment by mjohnson12** [comment]
We definitely could do that if we don't have to worry about backward compatibility.  It depends on how much change we want to force on users of the SDK when the upgrade.  Obviously less change is better but in some cases change is required.

**Comment by mjohnson12** [comment]
I have added an additional test for testing requesting a block by id.

**Comment by opi-smccoole** [comment]
> I have added an additional test for testing requesting a block by id.

Should we still have a test that takes the UInt64 to make validate that since it is deprecated but not yet removed?

**Comment by mjohnson12** [comment]
Good point.  If we leave in support for requesting by `UInt64` we should have a test for that.

**Comment by opi-smccoole** [comment]
For the parameter name another possibility might be `blockRequestId` or `requestBlockId` or `requestedBlockId`?  Otherwise I prefer `blockNumberOrId` over `blockNumOrIdString`.

**Comment by opi-smccoole** [comment]
> We definitely could do that if we don't have to worry about backward compatibility. It depends on how much change we want to force on users of the SDK when the upgrade. Obviously less change is better but in some cases change is required.

I actually like the ability to still pass in as a UInt64 for Block Number as well as the String for Block Id to be honest, because if we are working with block numbers that have been returned to us, they will be UInt64 and the developer will have to convert them.  Not a big deal but grates against the move away from "stringy" APIs in the iOS ecosystem.  I would say this looks like a good compromise though.  Let's change that internal name to one of the more palatable alternatives, and I'll approve.

**Comment by mjohnson12** [comment]
I've pushed out a new version where the property has been renamed and I removed the deprecation of the init so that the request can be initialized with either a `UInt64` or a `String`.

**Pull request merged**
