### PR TITLE
Make inline_traces optional

### PR DESCRIPTION
**Pull request by mschonvogel**
#218

### CODE REVIEW

**Comment by ealymbaev** [comment]
It should be merged urgently. Because now fetching actions list is impossible

**Comment by brandonfancher** [comment]
Thanks for the PR, @mschonvogel. We'll get this prioritized and addressed as soon as possible.

**Comment by mjohnson12** [comment]
EOSIO 1.8+ returns a different struct for traces.  `inline_traces` is no longer returned.  Instead of assigning it a default value we can just drop that property.  If anyone needs access to the traces they can dive into the raw response.

Thanks for reporting this.  We'll get this fixed and push out a new release as soon as possible.

**Comment by paulhyunkim** [comment]
Resolved by #226

**Pull request closed without merging**
